"""revokedtokens

Revision ID: 303ef70771ee
Revises: ebf1a7d0ebb7
Create Date: 2025-07-07 13:46:17.616430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303ef70771ee'
down_revision = 'ebf1a7d0ebb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token')
    # ### end Alembic commands ###
