"""added subtitle on projects

Revision ID: aa3bd78bc1d2
Revises: a989a89b63a8
Create Date: 2025-08-12 16:56:27.726073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3bd78bc1d2'
down_revision = 'a989a89b63a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
