"""added firstname and lastname

Revision ID: ebf1a7d0ebb7
Revises: d20f9c0bc0d3
Create Date: 2025-07-04 15:08:17.667251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf1a7d0ebb7'
down_revision = 'd20f9c0bc0d3'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=False, server_default='Unknown'))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
